@host=http://localhost:5555

### Add a user
POST {{host}}/signup
Content-Type: application/json

{
    "address": "5 avenue de la liberté",
    "email": "monemail1@mail.com",
    "firstname": "myfirstname",
    "lastname": "myname",
    "password": "hjfdklgbnfdxc",
    "passwordConfirm": "hjfdklgbnfdxc",
    "username": "monpseudo",
    "zip_code": "67000"
}

### Login
POST {{host}}/login
Content-Type: application/json

{
    "email": "monemail1@mail.com",
    "password": "hjfdklgbnfdxc"
}

### Get infos
GET {{host}}/infos
Authorization: 