@host=http://localhost:5555

### Add a user
POST {{host}}/signup
Content-Type: application/json

{
    "username": "ghjfvdgvfw",
    "lastname": "fzszaqsdpomikl",
    "firstname": "pmoiujydrfzsdxc",
    "email": "vbcghdfulizer@email.com",
    "password" : "bdekzbdfqej7854658",
    "address": "4 left street",
    "zip_code": "56203"
}

### Login
POST {{host}}/login
Content-Type: application/json

{
    "email": "vbcghdfulizer@email.com",
    "password": "bdekzbdfqej7854658"
}

### Get infos
GET {{host}}/infos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDMyMDU0ODAsImV4cCI6MTY0MzIwNTc4MH0.nbnaYv1_i4LY1syz2wRCIzuDKiVGZ6AOx_O-fksTr2Y