@host=http://localhost:5555

### Add a user
POST {{host}}/signup
Content-Type: application/json

{
    "address": "5 avenue de la liberté",
    "email": "test@test.com",
    "firstname": "myfirstname",
    "lastname": "myname",
    "password": "testtest",
    "passwordConfirm": "testtest",
    "username": "mypseudo",
    "zip_code": "67000"
}

### Login
POST {{host}}/login
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "testtest"
}

### Get infos
GET {{host}}/infos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJGFYSS93SU1pMEF1VWF4SE0vdW4wZ09lNE9kaG5Ld2dXRG5sWUFQMnRGd1RPanQzNHlQNXBTIiwiaWQiOjIzfSwiaWF0IjoxNjQzMzYxMDg0LCJleHAiOjE2NDMzNjI4ODR9.MmWYR7nk8LWGnd13_x5L1Z-I0d808sTsjUY2mSj7dXI

### Add an offer
POST {{host}}/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoyMSwiaWF0IjoxNjQzMjc4MjU1LCJleHAiOjE2NDMyNzg1NTV9.YHW_L49App6knMuLqeHOWkR4-vJwfACdJkVc8I6ihbw

{
  "title": "string",
  "infos": "string",
  "model": "string",
  "size": "string",
  "helmet": true,
  "lamps": true,
  "safety_lock": true,
  "photo": "string",
  "address": "string",
  "zip_code": 85000,
  "validity_start_date": "2022-01-01",
  "validity_end_date": "2022-01-01",
  "lender_id": null,
  "borrower_id": null
}

### GetFilteredOffers
POST {{host}}/offers
Content-Type: application/json

{
    "city": "5 avenue de la liberté",
    "size": "test@test.com",
    "model": "test@test.com",
    "helmet": "myfirstname",
    "lamps": "myname",
    "safety_lock": "testtest"
}